---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-server.fullname" . }}-config
type: Opaque
stringData:
  application.properties: |
    app.healthzGithubRepo={{ .Values.config.healthzGithubRepo }}
