apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-server.fullname" . }}-config
type: Opaque
stringData:
  application.properties: |
    app.healthzGithubRepo={{ .Values.config.healthzGithubRepo }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-server.fullname" . }}-config-env
type: Opaque
data:  
  GITHUB_LOGIN: {{ .Values.config.githubLogin | b64enc | quote }}
  GITHUB_OAUTH: {{ .Values.config.githubOauth | b64enc | quote }} 
  
