name: Acciones creación de imagenes docker y ejecución
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
         GITHUB_LOGIN: ${{ github.actor }}
         GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}   
         GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
         chmod +x gradlew        
         ./gradlew build -x test --no-daemon
     
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    env:
         GITHUB_LOGIN: ${{ github.actor }}
         GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}  
         GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}         
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Build java app
        run: |
          chmod +x gradlew      
          ./gradlew assemble
          echo $GITHUB_OAUTH
          echo $GITHUB_PACKAGES
          echo $GITHUB_LOGIN
      - name: Build docker image
        run: |
           ./gradlew docker        
      - name: Run docker container
        run: |
           ./gradlew dockerRun
      - name: Validate container
        run: |
           curl http://localhost:8080/metricsInfo?name=issues          
