name: AuditServer CI/CD pipeline
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew test --no-daemon
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build java app
        run: |
          echo "APP_VERSION=$(grep "version =" build.gradle | awk '{print $3}' | sed "s/'//g")" >> $GITHUB_ENV
          ./gradlew build --no-daemon
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: audit-server:${{ env.APP_VERSION }}
          build-args: VERSION=${{ env.APP_VERSION }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: audit-server
      - name: Deploy audit-server helm chart to local cluster
        run: |
          kind load docker-image audit-server:${{ env.APP_VERSION }} --name audit-server
          helm upgrade --install audit-server ./deploy/charts/audit-server \
            -f ./deploy/local.yaml \
            --set image.tag="${{ env.APP_VERSION }}" \
            --atomic \
            --timeout 2m0s
      - name: Validate audit-server deployment is successfully serving traffic
        run: |
          curl -f --connect-timeout 3 --retry 10 --retry-delay 5 http://localhost:8000/healthz
