name: AuditServer CI/CD pipeline
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
         GITHUB_LOGIN: ${{ secrets.LOGIN_GITHUB }}
         GITHUB_PACKAGES: ${{ secrets.PACKAGES_GITHUB }}   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - run: |
         chmod +x gradlew        
         ./gradlew build -x test --no-daemon
          
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    env:
         GITHUB_LOGIN: ${{ secrets.LOGIN_GITHUB }}
         GITHUB_PACKAGES: ${{ secrets.PACKAGES_GITHUB }}  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Tests
        run: |
          chmod +x gradlew      
          cp application.properties.sample application.properties
          sed -i "s/REPLACEME/${{ secrets.APP_GITHUB_TOKEN }}/g" application.properties
          ./gradlew test --no-daemon
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test]
    env:
         GITHUB_LOGIN: ${{ secrets.LOGIN_GITHUB }}
         GITHUB_PACKAGES: ${{ secrets.PACKAGES_GITHUB }}  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Build java app
        run: |
          chmod +x gradlew      
          echo "APP_VERSION=$(grep "version =" build.gradle | awk '{print $3}' | sed "s/'//g")" >> $GITHUB_ENV
          ./gradlew build -x test --no-daemon
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: audit-server:${{ env.APP_VERSION }}
          build-args: VERSION=${{ env.APP_VERSION }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: audit-server
      - name: Deploy audit-server helm chart to local cluster
        run: |
          kind load docker-image audit-server:${{ env.APP_VERSION }} --name audit-server
          helm upgrade --install audit-server ./deploy/charts/audit-server \
            -f ./deploy/local.yaml \
            --set image.tag="${{ env.APP_VERSION }}" \
            --set config.githubToken="${{ secrets.APP_GITHUB_TOKEN }}" \
            --atomic \
            --debug \
            --timeout 5m0s
      - name: Validate audit-server deployment is successfully serving traffic
        run: |
          kubectl port-forward svc/audit-server 8000:80 &
          sleep 10
          curl -f --connect-timeout 3 --retry 10 --retry-delay 5 http://localhost:8000/healthz

